const authConstants = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    LOGIN_RESET: 'USER_LOGIN_RESET',

    LOGOUT: 'USER_LOGOUT',
};

const registerConstants = {
    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    REGISTER_RESET: 'USER_REGISTER_RESET',
};

export { authConstants, registerConstants };