export const stacks = {
    tabs: {name: 'Tabs'},
    home: {name: 'Home', title: 'Home'},
    createPost: {name: 'CreatePost', title: 'Add a new post'},
    newsFeed: {name: 'Newsfeed', title: 'Newsfeed'},
    comment: {name: 'Comment', title: 'Comment'},
    profile: {name: 'Profile', title: 'User profile'},
    signIn: {name: 'signIn', title: 'Sign In'},
    signUp: {name: 'signUp', title: 'Sign Up'},
    signOut: {name: 'signOut', title: 'Sign Out'},
    changePW: {name: 'changePW', title: 'Change Password'},
    advance: {name:'advance', title:'Advance'},
    personalInformation: {name:'personalInformation', title:'Personal Information'},
    notification: {name: 'Notification', title:'Notification'},
    listFriend: {name: 'listFriend', title:'List Friend'},
    friendRequest: {name: 'friendRequest', title:'List Friend Request'},
    chatScreen: {name: 'chat', title:'Chat'},
    searchFriend: {name: 'search', title:'Search'},
    messageScreen: {name: 'message', title:'Message'},
    chatSetting: {name: 'setting', title:'Chat Setting'},
    mediaPicker: {name: 'mediaPicker', title: 'Media picker'},
    friendTabs: {name: 'friendTabs', title: 'Friends'},
};

